### ISSUE TITLE
haxe value exception

### ISSUE THREAD

**Issue by fnfporterhi** [LEVIXDDLMAO/Levipsych_htmlv3#1]

**Comment by LEVIXDDLMAO** [comment]
dude you cant read or something? I already said dont open issues, there is tons of bugs ik ik like bruh just read for once like god damn

**Comment by fnfporterhi** [comment]
im sorry i didnt see the description


I'm sorry I pissed you off

**Comment by fnfporterhi** [comment]
sorry

**Comment by LEVIXDDLMAO** [comment]
im not pissed, you just need to read. and look
